name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Compile Feather
        run: | 
          agvtool new-version -all $(git rev-parse HEAD)
          make
          mkdir upload
          mv packages/* upload/

      - name: Extract Version
        id: get_version
        run: |
          VERSION=$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Feather v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            upload/*
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
